### ISSUE TITLE
What's the meaning of "# Warning: this won't be cleaned up, which might be an issue if you run it # with the local builder."

### ISSUE THREAD

**Issue by cesarvarela** [Philmod/gcb-docker-compose#11]
thanks

**Comment by Philmod** [comment]
`docker-compose up -d` run the containers in the background. There is no step to clean this up. That's not a problem on GCB because the VM is destroyed after the build anyway. But if you use the [local builder](https://cloud.google.com/cloud-build/docs/build-debug-locally), the containers will keep running on your machine.
